In [2]:
#question1
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x.tolist()

[[1, 2, 3], [4, 5, 6]]

In [3]:
#question 2
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x.trace()

15

In [8]:
#question 3 
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print (x[x>3])

[4 5 6]


In [16]:
#question 4 
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
print (x+y)

[[ 8 10 12]
 [14 16 18]]


In [23]:
#question 5 
import numpy as np 
x = np.array([[1,2,3],[4,5,6]])
print (x.mean()-y)

[[-3.5 -4.5 -5.5]
 [-6.5 -7.5 -8.5]]
